%% De_53 - Khách hàng thanh toán
classDiagram
    class SanMini {
        +maSan
        +tenSan
        +loaiSan
        +giaThueMotBuoi
    }


    class KhachHang {
        +maKhachHang
        +tenKhachHang
        +soDienThoai
    }


    class PhieuDatSan {
        +maPhieuDat
        +ngayLamHopDong
        +thongTinChuSan
        +soTienDatCoc
        +ngayDatCoc
        +tongTienThueDuKien
    }


    class ChiTietDatSan {
        +giaThueMotBuoi
        +khungGioThueTrongTuan
        +ngayBatDau
        +ngayKetThuc
        +tongSoBuoi
        +tongTienDuKien
    }

    class BuoiThueSan {
        +ngayThue
        +khungGio
        +tongTienHang
    }


    class MatHang {
        +maMatHang
        +tenMatHang
        +donGia
        +soLuongTon
    }


    class ChiTietSuDungHang {
        +gia
        +soLuongDung
        +thanhTien
    }


    class HoaDonThanhToan {
        +maHoaDon
        +ngayThanhToan
        +tongTienSan
        +tongTienHang
        +tongTienThanhToan
    }
    KhachHang "1" -- "0..*" PhieuDatSan : đặt sân
    PhieuDatSan "1" *-- "1..*" ChiTietDatSan : gồm
    ChiTietDatSan "0..*" -- "1" SanMini : sân thuê
    ChiTietDatSan "1" *-- "1..*" BuoiThueSan : gồm buổi thuê
    BuoiThueSan "1" *-- "0..*" ChiTietSuDungHang : dùng hàng
    ChiTietSuDungHang "0..*" -- "1" MatHang : mặt hàng
    PhieuDatSan "1" -- "0..1" HoaDonThanhToan : thanh toán

