classDiagram
    class Ban {
        +maBan
        +tenBan
        +soLuongKhachToiDa
        +moTa
    }

    class KhachHang {
        +maKhachHang
        +tenKhachHang
        +soDienThoai
        +email
        +diaChi
    }

    class MonAn {
        +maMon
        +loai
        +tenMon
        +moTa
        +giaHienTai
    }

    class Combo {
        +maCombo
        +tenCombo
        +giaHienTai
    }

    class ChiTietCombo {
        +soLuong
    }

    class PhieuDatBan {
        +maPhieuDat
        +ngayDat
        +gioDat
        +soLuongKhach
    }

    class PhieuGoiMon {
        +maPhieuGoi
        +ngayGioGoi
    }

    class ChiTietGoiMon {
        +donGia
        +soLuong
        +thanhTien
    }

    class NhanVien {
        +maNhanVien
        +tenNhanVien
    }

    class PhieuGiamGia {
        +maPhieuGiamGia
        +soTienGiam
    }

    class HoaDon {
        +maHoaDon
        +ngayGioThanhToan
        +tongTien
    }
    KhachHang "1" -- "0..*" PhieuDatBan : đặt bàn
    PhieuDatBan "0..*" -- "1" Ban : đặt
    Ban "1" -- "0..*" PhieuGoiMon : phát sinh
    PhieuGoiMon "1" *-- "1..*" ChiTietGoiMon : gồm
    ChiTietGoiMon "0..*" -- "0..1" MonAn : món ăn
    ChiTietGoiMon "0..*" -- "0..1" Combo : combo
    Combo "1" *-- "1..*" ChiTietCombo : gồm
    ChiTietCombo "0..*" -- "1" MonAn : món ăn
    PhieuGoiMon "1" -- "0..1" HoaDon : thanh toán
    NhanVien "1" -- "0..*" HoaDon : thanh toán
    KhachHang "0..1" -- "0..*" HoaDon : nhận hóa đơn
    HoaDon "0..1" -- "0..1" PhieuGiamGia : áp dụng


