%% De_57 - Cho khách thanh toán theo hạn
classDiagram
    class KhachHang {
        +maKhachHang
        +tenKhachHang
        +soDienThoai
        +diaChi
    }


    class HopDongTraGop {
        +maHopDong
        +thongTinDaiDienCongTy
        +ngayKi
        +tongTien
        +thoiHanVay
        +laiSuatNam
    }


    class DoiTac {
        +maDoiTac
        +tenDoiTac
        +diaChiChiNhanh
    }


    class MatHang {
        +maMatHang
        +tenMatHang
        +donViTinh
        +giaNiemYet
    }


    class ChiTietHopDong {
        +donGia
        +soLuong
        +thanhTien
    }


    class DotThanhToan {
        +ngayPhaiThanhToan
        +tongTienThanhToan
        +soTienDaThanhToan
        +tongDuNoConLai
        +trangThaiThanhToan
    }


    class HoaDonThanhToan {
        +maHoaDon
        +ngayThanhToan
        +tongTienThanhToan
        +tongDuNoConLai
        +hinhThucThanhToan
    }


    class ChiTietThanhToanDot {
        +soTienThanhToan
    }

    KhachHang "1" -- "0..*" HopDongTraGop : ký
    DoiTac "1" -- "0..*" HopDongTraGop : bán hàng qua
    HopDongTraGop "1" *-- "1..*" ChiTietHopDong : gồm
    ChiTietHopDong "0..*" -- "1" MatHang : mặt hàng
    HopDongTraGop "1" *-- "1..*" DotThanhToan : lịch trả góp
    HopDongTraGop "1" -- "0..*" HoaDonThanhToan : phát sinh hóa đơn
    HoaDonThanhToan "1" *-- "1..*" ChiTietThanhToanDot : gồm
    ChiTietThanhToanDot "0..*" -- "1" DotThanhToan : thanh toán cho đợt

