%% De_55 - Thống kê khung giờ được thuê nhiều
classDiagram
    class SanMini {
        +maSan
        +tenSan
        +loaiSan
        +giaThueMotBuoi
    }


    class KhachHang {
        +maKhachHang
        +tenKhachHang
        +soDienThoai
    }


    class PhieuDatSan {
        +maPhieuDat
        +ngayLamHopDong
        +thongTinChuSan
        +soTienDatCoc
        +ngayDatCoc
        +tongTienThueDuKien
    }


    class ChiTietDatSan {
        +giaThueMotBuoi
        +khungGioThueTrongTuan
        +ngayBatDau
        +ngayKetThuc
        +tongSoBuoi
        +tongTienDuKien
    }


    class BuoiThueSan {
        +ngayThue
        +khungGio
        +tongTienHang
    }


    class HoaDonThanhToan {
        +maHoaDon
        +ngayThanhToan
        +tongTienSan
        +tongTienHang
        +tongTienThanhToan
    }

    SanMini "0..*" -- "0..1" SanMini : ghép thành sân lớn
    KhachHang "1" -- "0..*" PhieuDatSan : đặt sân
    PhieuDatSan "1" *-- "1..*" ChiTietDatSan : gồm
    ChiTietDatSan "0..*" -- "1" SanMini : sân thuê
    PhieuDatSan "1" *-- "0..*" BuoiThueSan : phát sinh buổi thuê
    PhieuDatSan "1" -- "0..1" HoaDonThanhToan : thanh toán

